title: Page par Default

status:
  draft: Brouillon
  listed: Publié

columns:
  main:
    width: 2/3
    # CONTENT SECTION
    fields:
      content_headline:
        label: 🟦 CONTENU
        type: headline
        numbered: false

      content_subtitle:
        label: Sous-titre
        type: text
        required: true

      content_body:
        label: Contenu
        type: writer
        nodes:
          - paragraph
        marks:
          - link

      content_descritpio:
        label: Descriptif technique
        type: writer
        nodes:
          - paragraph
        marks:
          - link



  sidebar:
    width: 1/3
    # HERO SECTION
    fields:
      info_headline:
        label: 🟣 Infos
        type: headline
        numbered: false
      info_bio_studio:
        label: Bio exposant·e·xs
        type: writer
        nodes:
          - paragraph
        marks:
          - link
      info_link_website:
        label: Site web
        type: url
      info_link_social:
        label: Lien Instagram
        type: url
      info_image:
        label: Image(s)
        image:
          cover: true
        type: files
        multiple: true
        layout: cards
        uploads:
          template: image


