title: Contenu du site

columns:
  left:
    width: 2/3
    sections:
      pages_infos:
        label: Pages
        type: pages
        layout: cards
        image:
          query: false
          ratio: 3/1
          back: "rgb(196 226 254)"
        templates:
          - home
          - apropos
          - infos
        create:
          - home
          - apropos
          - infos

  right:
    width: 1/3
    sections:
      pages_exposants:
        label: Exposant·e·s
        type: pages
        layout: cards
        image:
          query: false
          ratio: 3/1
          back: "rgb(196 226 254)"
        templates:
          - exposants
        create:
          - exposants
        max: 1

      pages_programme:
        label: Programme
        type: pages
        layout: cards
        image:
          query: false
          ratio: 3/1
          back: "rgb(196 226 254)"
        templates:
          - programme
        create:
          - programme
        max: 1
