name: Deploy Kirby to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy Kirby via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 57-102620.ssh.hosting-ik.com
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd ~/upload-back || mkdir -p ~/upload-back
          git pull origin main || git clone https://github.com/Milo69/upload-back.git ~/upload-back
          cd ~/upload-back
          composer install --no-dev --optimize-autoloader
          
    - name: Upload files via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 57-102620.ssh.hosting-ik.com
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "./*"
        target: "~/upload-back/"
        rm: true
        exclude: |
          .git
          .DS_Store